name: Build Periodic Backup plugin

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build on JDK ${{ matrix.jdk }}
    strategy:
      matrix:
        jdk: [ '11', '17' ]
    runs-on: ubuntu-latest

    steps:
      - name: Sync Repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.jdk }}
      - name: Build with Gradle
        run: mvn --batch-mode --update-snapshots verify

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: periodicbackup-plugin-artifacts
          path: target/*.hpi